project_id = "ahzmgjedjlzfawexlbrm"

[functions.process-recurring-invoices]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false

[functions.invite-team-member]
verify_jwt = false

[functions.send-overdue-reminders]
verify_jwt = false
